server.port=8080
spring.thymeleaf.cache=true
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.suffix=.html

#\u914D\u7F6E\u6587\u4EF6\u5B58\u653E\u76EE\u5F55
file.upload-dir=/tmp/uploads


spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=0
#spring.servlet.multipart.location=
#\u5355\u6587\u4EF6\u5927\u5C0F\u9650\u5236
spring.servlet.multipart.max-file-size=1MB
#\u603B\u6587\u4EF6\u5927\u5C0F\u9650\u5236
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.resolve-lazily=false